### ISSUE TITLE
Vite 4 support

### ISSUE THREAD

**Issue by zepfietje** [spatie/flare-vite-plugin-sourcemap-uploader#3]
New Laravel projects ship with Vite 4 out of the box, but this package doesn't support Vite 4 yet.

Also, this plugin blocks me from upgrading my existing projects to Vite 4.

**Comment by Sam-Apostel** [comment]
v1.0.2 with vite 4 support has now been released.

**Comment by zepfietje** [comment]
Quick, thanks! 🔥
